{{- $root := . -}}
  {{- range $app := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $app.name }}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: "team-test"
spec:
  project: default
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.docker.internal:6443"
  source:
    path: {{ $app.path }}
    repoURL: "https://github.com/hansso90/argocd-infra-example.git"
    targetRevision: {{ $app.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - {{ $app.values }}
---
{{ end }}