apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qi-infra-app-of-apps
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/app-of-apps
    repoURL: 'git@github.com:Hansso90/argocd-infra-example.git'
    helm:
      valueFiles:
        - values.yaml
  project: qi-infra