apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-foo-app-of-apps
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.docker.internal:6443'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  source:
    path: apps/app-of-apps
    repoURL: 'https://github.com/hansso90/argocd-infra-example.git'
    helm:
      valueFiles:
        - values.yaml
  project: default